#!/bin/bash
sed -e "1,/^=== TAG ===/d" "$0" | openssl enc -d -aes-128-cbc -a 2> /dev/null
exit
=== TAG ===
U2FsdGVkX18X0LWn/1WA4fXdbCb9FN10vSJTSTQFNYg4t19TCBf2hewHWFc1DU9T
ECQj7pochf2JXtTjg/9SweQrf7M7G/u1jWTWeCedJxC7QFjeVHkKOn0fz2WNarmU
7JSbSH7gEITDlq8humrbzrFiziMLdHmWXlyve+Z5sL1XCvyKO7epyluYGHT5e1EE
6tQL5WrmfAix1LB2hgJoVnQ/kSgizkGERHXs2Wu/oU7gohxY3hL0HdOrBarlGsuH
Q/8UU64BCgDCLk/F/FyjX0EfXNGypZ9zC/kUqfubEPI=
