#!/bin/bash
sed -e "1,/^=== TAG ===/d" "$0" | openssl enc -d -aes-128-cbc -a 2> /dev/null
exit
=== TAG ===
U2FsdGVkX1/W8sXlAF28zAlHPubzb1Je+foX6CEz/LarQMcJdAUZyXek23lkG4/L
E9FJe3Wgu2XwHt6AAw1Jw4Ebk7mKrXlYcOar2iIxjaMdCEFy17JDJQxTzkjhLL/6
FU2hrEsfzerKGlbDZ7UTsryWhWahDxicJo9d9pHbfY5V6XJWyjfRpanu+8ffz36P
npxYOwO9YvlDPLr6zfdWXLCGCzY8hvqm7EZgrLjs3G2CLi8s+z1WGoCUUkkJsDK7
vS8NJbBqgLtmB9sNvjCzYw==
